//
//  FontHeader.h
//  SDBank_iOS
//
//  Created by sdebank on 2021/8/24.
//  Copyright © 2021 Alibaba. All rights reserved.
//

#ifndef FontHeader_h
#define FontHeader_h

//kFont
#define kFont_10 [UIFont systemFontOfSize:10]
#define kFont_11 [UIFont systemFontOfSize:11]
#define kFont_12 [UIFont systemFontOfSize:12]
#define kFont_13 [UIFont systemFontOfSize:13]
#define kFont_14 [UIFont systemFontOfSize:14]
#define kFont_15 [UIFont systemFontOfSize:15]
#define kFont_16 [UIFont systemFontOfSize:16]
#define kFont_17 [UIFont systemFontOfSize:17]
#define kFont_18 [UIFont systemFontOfSize:18]
#define kFont_19 [UIFont systemFontOfSize:19]
#define kFont_20 [UIFont systemFontOfSize:20]

//PingFangSC-Medium 字体
#define kFont_PFSC_medium_x(x) [UIFont fontWithName:@"PingFangSC-Medium" size:x]
#define kFont_PFSC_medium_10 [UIFont fontWithName:@"PingFangSC-Medium" size:10]
#define kFont_PFSC_medium_11 [UIFont fontWithName:@"PingFangSC-Medium" size:11]
#define kFont_PFSC_medium_12 [UIFont fontWithName:@"PingFangSC-Medium" size:12]
#define kFont_PFSC_medium_13 [UIFont fontWithName:@"PingFangSC-Medium" size:13]
#define kFont_PFSC_medium_14 [UIFont fontWithName:@"PingFangSC-Medium" size:14]
#define kFont_PFSC_medium_15 [UIFont fontWithName:@"PingFangSC-Medium" size:15]
#define kFont_PFSC_medium_16 [UIFont fontWithName:@"PingFangSC-Medium" size:16]
#define kFont_PFSC_medium_17 [UIFont fontWithName:@"PingFangSC-Medium" size:17]
#define kFont_PFSC_medium_18 [UIFont fontWithName:@"PingFangSC-Medium" size:18]
#define kFont_PFSC_medium_19 [UIFont fontWithName:@"PingFangSC-Medium" size:19]
#define kFont_PFSC_medium_20 [UIFont fontWithName:@"PingFangSC-Medium" size:20]

#define kFont_PFSC_semibold_x(x) [UIFont fontWithName:@"PingFangSC-Semibold" size:x]
#define kFont_PFSC_semibold_10 [UIFont fontWithName:@"PingFangSC-Semibold" size:10]
#define kFont_PFSC_semibold_11 [UIFont fontWithName:@"PingFangSC-Semibold" size:11]
#define kFont_PFSC_semibold_12 [UIFont fontWithName:@"PingFangSC-Semibold" size:12]
#define kFont_PFSC_semibold_13 [UIFont fontWithName:@"PingFangSC-Semibold" size:13]
#define kFont_PFSC_semibold_14 [UIFont fontWithName:@"PingFangSC-Semibold" size:14]
#define kFont_PFSC_semibold_15 [UIFont fontWithName:@"PingFangSC-Semibold" size:15]
#define kFont_PFSC_semibold_16 [UIFont fontWithName:@"PingFangSC-Semibold" size:16]
#define kFont_PFSC_semibold_17 [UIFont fontWithName:@"PingFangSC-Semibold" size:17]
#define kFont_PFSC_semibold_18 [UIFont fontWithName:@"PingFangSC-Semibold" size:18]
#define kFont_PFSC_semibold_19 [UIFont fontWithName:@"PingFangSC-Semibold" size:19]
#define kFont_PFSC_semibold_20 [UIFont fontWithName:@"PingFangSC-Semibold" size:20]

#define kFont_PFSC_regular_x(x) [UIFont fontWithName:@"PingFangSC-Regular" size:x]
#define kFont_PFSC_regular_10 [UIFont fontWithName:@"PingFangSC-Regular" size:10]
#define kFont_PFSC_regular_11 [UIFont fontWithName:@"PingFangSC-Regular" size:11]
#define kFont_PFSC_regular_12 [UIFont fontWithName:@"PingFangSC-Regular" size:12]
#define kFont_PFSC_regular_13 [UIFont fontWithName:@"PingFangSC-Regular" size:13]
#define kFont_PFSC_regular_14 [UIFont fontWithName:@"PingFangSC-Regular" size:14]
#define kFont_PFSC_regular_15 [UIFont fontWithName:@"PingFangSC-Regular" size:15]
#define kFont_PFSC_regular_16 [UIFont fontWithName:@"PingFangSC-Regular" size:16]
#define kFont_PFSC_regular_17 [UIFont fontWithName:@"PingFangSC-Regular" size:17]
#define kFont_PFSC_regular_18 [UIFont fontWithName:@"PingFangSC-Regular" size:18]
#define kFont_PFSC_regular_19 [UIFont fontWithName:@"PingFangSC-Regular" size:19]
#define kFont_PFSC_regular_20 [UIFont fontWithName:@"PingFangSC-Regular" size:20]

#define kFont_PFSC_light_x(x) [UIFont fontWithName:@"PingFangSC-Light" size:x]
#define kFont_PFSC_light_10 [UIFont fontWithName:@"PingFangSC-Light" size:10]
#define kFont_PFSC_light_11 [UIFont fontWithName:@"PingFangSC-Light" size:11]
#define kFont_PFSC_light_12 [UIFont fontWithName:@"PingFangSC-Light" size:12]
#define kFont_PFSC_light_13 [UIFont fontWithName:@"PingFangSC-Light" size:13]
#define kFont_PFSC_light_14 [UIFont fontWithName:@"PingFangSC-Light" size:14]
#define kFont_PFSC_light_15 [UIFont fontWithName:@"PingFangSC-Light" size:15]
#define kFont_PFSC_light_16 [UIFont fontWithName:@"PingFangSC-Light" size:16]
#define kFont_PFSC_light_17 [UIFont fontWithName:@"PingFangSC-Light" size:17]
#define kFont_PFSC_light_18 [UIFont fontWithName:@"PingFangSC-Light" size:18]
#define kFont_PFSC_light_19 [UIFont fontWithName:@"PingFangSC-Light" size:19]
#define kFont_PFSC_light_20 [UIFont fontWithName:@"PingFangSC-Light" size:20]

// HelveticaNeue-CondensedBold
#define kFont_HN_CondensedBold_x(x) [UIFont fontWithName:@"HelveticaNeue-CondensedBold" size:x]
#define kFont_HN_CondensedBold_10 [UIFont fontWithName:@"HelveticaNeue-CondensedBold" size:10]
#define kFont_HN_CondensedBold_11 [UIFont fontWithName:@"HelveticaNeue-CondensedBold" size:11]
#define kFont_HN_CondensedBold_12 [UIFont fontWithName:@"HelveticaNeue-CondensedBold" size:12]
#define kFont_HN_CondensedBold_13 [UIFont fontWithName:@"HelveticaNeue-CondensedBold" size:13]
#define kFont_HN_CondensedBold_14 [UIFont fontWithName:@"HelveticaNeue-CondensedBold" size:14]
#define kFont_HN_CondensedBold_15 [UIFont fontWithName:@"HelveticaNeue-CondensedBold" size:15]
#define kFont_HN_CondensedBold_16 [UIFont fontWithName:@"HelveticaNeue-CondensedBold" size:16]
#define kFont_HN_CondensedBold_17 [UIFont fontWithName:@"HelveticaNeue-CondensedBold" size:17]
#define kFont_HN_CondensedBold_18 [UIFont fontWithName:@"HelveticaNeue-CondensedBold" size:18]
#define kFont_HN_CondensedBold_19 [UIFont fontWithName:@"HelveticaNeue-CondensedBold" size:19]
#define kFont_HN_CondensedBold_20 [UIFont fontWithName:@"HelveticaNeue-CondensedBold" size:20]
#define kFont_HN_CondensedBold_24 [UIFont fontWithName:@"HelveticaNeue-CondensedBold" size:24]

/**< 加粗号字体> */
#define kFont_10_weight_x(x) [UIFont systemFontOfSize:10 weight:x]
#define kFont_11_weight_x(x) [UIFont systemFontOfSize:11 weight:x]
#define kFont_12_weight_x(x) [UIFont systemFontOfSize:12 weight:x]
#define kFont_13_weight_x(x) [UIFont systemFontOfSize:13 weight:x]
#define kFont_14_weight_x(x) [UIFont systemFontOfSize:14 weight:x]
#define kFont_15_weight_x(x) [UIFont systemFontOfSize:15 weight:x]
#define kFont_16_weight_x(x) [UIFont systemFontOfSize:16 weight:x]
#define kFont_17_weight_x(x) [UIFont systemFontOfSize:17 weight:x]
#define kFont_18_weight_x(x) [UIFont systemFontOfSize:18 weight:x]
#define kFont_19_weight_x(x) [UIFont systemFontOfSize:19 weight:x]
#define kFont_20_weight_x(x) [UIFont systemFontOfSize:20 weight:x]

#define kFont_COPPERPLATE_LIGHT_20 [UIFont fontWithName:@"COPPERPLATE-LIGHT" size:20]
#define kFont_COPPERPLATE_20 [UIFont fontWithName:@"COPPERPLATE" size:20]

#define kFont_IOS_Italic_20 [UIFont fontWithName:@"IowanOldStyle-Italic" size:20]
#define kFont_IOS_Roman_20 [UIFont fontWithName:@"IowanOldStyle-Roman" size:20]
#define kFont_IOS_BoldItalic_20 [UIFont fontWithName:@"IowanOldStyle-BoldItalic" size:20]
#define kFont_IOS_Bold_20 [UIFont fontWithName:@"IowanOldStyle-Bold" size:20]

#define kFont_KT_Regular_20 [UIFont fontWithName:@"KohinoorTelugu-Regular" size:20]
#define kFont_KT_Medium_20 [UIFont fontWithName:@"KohinoorTelugu-Medium" size:20]
#define kFont_KT_Light_20 [UIFont fontWithName:@"KohinoorTelugu-Light" size:20]

#define kFont_T_20 [UIFont fontWithName:@"Thonburi" size:20]
#define kFont_T_Bold_20 [UIFont fontWithName:@"Thonburi-Bold" size:20]
#define kFont_T_Light_20 [UIFont fontWithName:@"Thonburi-Light" size:20]

#define kFont_CNPS_BoldMT_20 [UIFont fontWithName:@"CourierNewPS-BoldMT" size:20]
#define kFont_CNPS_ItalicMT_20 [UIFont fontWithName:@"CourierNewPS-ItalicMT" size:20]
#define kFont_CNPSMT_20 [UIFont fontWithName:@"CourierNewPSMT" size:20]

#define kFont_GS_Italic_20 [UIFont fontWithName:@"GillSans-Italic" size:20]

#define kFont_Khmer_Sangam_MN_20 [UIFont fontWithName:@"Khmer Sangam MN" size:20]
#define kFont_Kohinoor_Telugu_20 [UIFont fontWithName:@"Kohinoor Telugu" size:20]
#define kFont_Snell_Roundhand_20 [UIFont fontWithName:@"Snell Roundhand" size:20]
#define kFont_Academy_Engraved_LET_20 [UIFont fontWithName:@"Academy Engraved LET" size:20]
#define kFont_Marker_Felt_20 [UIFont fontWithName:@"Marker Felt" size:20]
#define kFont_Avenir_20 [UIFont fontWithName:@"Avenir" size:20]
#define kFont_Geeza_Pro_20 [UIFont fontWithName:@"Geeza Pro" size:20]
#define kFont_Arial_Rounded_MT_Bold_20 [UIFont fontWithName:@"Arial Rounded MT Bold" size:20]
#define kFont_Trebuchet_MS_20 [UIFont fontWithName:@"Trebuchet MS" size:20]
#define kFont_Arial_20 [UIFont fontWithName:@"Arial" size:20]
#define kFont_Menlo_20 [UIFont fontWithName:@"Menlo" size:20]
#define kFont_Malayalam_Sangam_MN_20 [UIFont fontWithName:@"Malayalam Sangam MN" size:20]
#define kFont_Bradley_Hand_20 [UIFont fontWithName:@"Bradley Hand" size:20]
#define kFont_Bodoni_72_Oldstyle_20 [UIFont fontWithName:@"Bodoni 72 Oldstyle" size:20]
#define kFont_Cochin_20 [UIFont fontWithName:@"Cochin" size:20]
#define kFont_Sinhala_Sangam_MN_20 [UIFont fontWithName:@"Sinhala Sangam MN" size:20]
#define kFont_PingFang_HK_20 [UIFont fontWithName:@"PingFang HK" size:20]
#define kFont_Iowan_Old_Style_20 [UIFont fontWithName:@"Iowan Old Style" size:20]
#define kFont_Kohinoor_Bangla_20 [UIFont fontWithName:@"Kohinoor Bangla" size:20]
#define kFont_Damascus_20 [UIFont fontWithName:@"Damascus" size:20]
#define kFont_Farah_20 [UIFont fontWithName:@"Farah" size:20]
#define kFont_Papyrus_20 [UIFont fontWithName:@"Papyrus" size:20]
#define kFont_Verdana_20 [UIFont fontWithName:@"Verdana" size:20]
#define kFont_Zapf_Dingbats_20 [UIFont fontWithName:@"Zapf Dingbats" size:20]
#define kFont_Avenir_Next_Condensed_20 [UIFont fontWithName:@"Avenir Next Condensed" size:20]
#define kFont_Courier_20 [UIFont fontWithName:@"Courier" size:20]
#define kFont_Hoefler_Text_20 [UIFont fontWithName:@"Hoefler Text" size:20]
#define kFont_Euphemia_UCAS_20 [UIFont fontWithName:@"Euphemia UCAS" size:20]
#define kFont_Helvetica_20 [UIFont fontWithName:@"Helvetica" size:20]
#define kFont_Lao_Sangam_MN_20 [UIFont fontWithName:@"Lao Sangam MN" size:20]
#define kFont_Hiragino_Mincho_ProN_20 [UIFont fontWithName:@"Hiragino Mincho ProN" size:20]
#define kFont_Bodoni_Ornaments_20 [UIFont fontWithName:@"Bodoni Ornaments" size:20]
#define kFont_Apple_Color_Emoji_20 [UIFont fontWithName:@"Apple Color Emoji" size:20]
#define kFont_Mishafi_20 [UIFont fontWithName:@"Mishafi" size:20]
#define kFont_Optima_20 [UIFont fontWithName:@"Optima" size:20]
#define kFont_Devanagari_Sangam_MN_20 [UIFont fontWithName:@"Devanagari Sangam MN" size:20]
#define kFont_PingFang_SC_20 [UIFont fontWithName:@"PingFang SC" size:20]
#define kFont_Savoye_LET_20 [UIFont fontWithName:@"Savoye LET" size:20]
#define kFont_Times_New_Roman_20 [UIFont fontWithName:@"Times New Roman" size:20]
#define kFont_Kailasa_20 [UIFont fontWithName:@"Kailasa" size:20]
#define kFont_Telugu_Sangam_MN_20 [UIFont fontWithName:@"Telugu Sangam MN" size:20]
#define kFont_Heiti_SC_20 [UIFont fontWithName:@"Heiti SC" size:20]
#define kFont_Apple_SD_Gothic_Neo_20 [UIFont fontWithName:@"Apple SD Gothic Neo" size:20]
#define kFont_Futura_20 [UIFont fontWithName:@"Futura" size:20]
#define kFont_Bodoni_72_20 [UIFont fontWithName:@"Bodoni 72" size:20]
#define kFont_Baskerville_20 [UIFont fontWithName:@"Baskerville" size:20]
#define kFont_Symbol_20 [UIFont fontWithName:@"Symbol" size:20]
#define kFont_Heiti_TC_20 [UIFont fontWithName:@"Heiti TC" size:20]
#define kFont_Copperplate_20 [UIFont fontWithName:@"Copperplate" size:20]
#define kFont_Party_LET_20 [UIFont fontWithName:@"Party LET" size:20]
#define kFont_American_Typewriter_20 [UIFont fontWithName:@"American Typewriter" size:20]
#define kFont_Chalkboard_SE_20 [UIFont fontWithName:@"Chalkboard SE" size:20]
#define kFont_Avenir_Next_20 [UIFont fontWithName:@"Avenir Next" size:20]
#define kFont_Bangla_Sangam_MN_20 [UIFont fontWithName:@"Bangla Sangam MN" size:20]
#define kFont_Noteworthy_20 [UIFont fontWithName:@"Noteworthy" size:20]
#define kFont_Hiragino_Sans_20 [UIFont fontWithName:@"Hiragino Sans" size:20]
#define kFont_Zapfino_20 [UIFont fontWithName:@"Zapfino" size:20]
#define kFont_Tamil_Sangam_MN_20 [UIFont fontWithName:@"Tamil Sangam MN" size:20]
#define kFont_Chalkduster_20 [UIFont fontWithName:@"Chalkduster" size:20]
#define kFont_Arial_Hebrew_20 [UIFont fontWithName:@"Arial Hebrew" size:20]
#define kFont_Georgia_20 [UIFont fontWithName:@"Georgia" size:20]
#define kFont_Helvetica_Neue_20 [UIFont fontWithName:@"Helvetica Neue" size:20]
#define kFont_Gill_Sans_20 [UIFont fontWithName:@"Gill Sans" size:20]
#define kFont_Kohinoor_Devanagari_20 [UIFont fontWithName:@"Kohinoor Devanagari" size:20]
#define kFont_Palatino_20 [UIFont fontWithName:@"Palatino" size:20]
#define kFont_Courier_New_20 [UIFont fontWithName:@"Courier New" size:20]
#define kFont_Didot_20 [UIFont fontWithName:@"Didot" size:20]
#define kFont_PingFang_TC_20 [UIFont fontWithName:@"PingFang TC" size:20]
#define kFont_Bodoni_72_Smallcaps_20 [UIFont fontWithName:@"Bodoni 72 Smallcaps" size:20]


#define kIs375OrMax (kSCREEN_WIDTH < 375)
#define kFont_auto_reg_12 (kIs375OrMax ? ([UIFont fontWithName:@"PingFangSC-Regular" size:11]) : ([UIFont fontWithName:@"PingFangSC-Regular" size:12]))
#define kFont_auto_reg_13 (kIs375OrMax ? ([UIFont fontWithName:@"PingFangSC-Regular" size:12]) : ([UIFont fontWithName:@"PingFangSC-Regular" size:13]))

#endif /* FontHeader_h */
