name: afjflutter
description: A new Flutter module project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.4

  flutter_bloc: ^8.0.1 # 状态管理
  stream_transform: ^2.0.0
  equatable: ^2.0.3 # 相等辅助

  package_info_plus: ^1.3.0 # 应用包信息
  r_upgrade: ^0.3.8+2 # 应用升级

  sqflite: ^2.0.2+1 # 数据库
  sqflite_common_ffi: ^2.1.1 # 数据库
  shared_preferences: ^2.0.13 # xml 固化
  path_provider: ^2.0.11 # 路径

  dio: ^4.0.4 # 网络请求
  jwt_decoder: ^2.0.1 # jwt 解析

  toggle_rotate: ^1.0.1
  flutter_star: ^1.0.2 # 星星组件
  dash_painter: ^1.0.2
  wrapper: ^1.0.2

  url_launcher: ^6.1.9 # url
  share_plus: ^6.3.1 # 文字分享
  flutter_svg: ^2.0.1
  intl: ^0.17.0
  platform: ^3.1.0
  image: ^3.1.0
  flutter_spinkit: ^5.1.0 # loading
  flutter_markdown: ^0.6.4 # markdown
  file_selector: ^0.9.2+2
  window_manager: ^0.2.8 #桌面尺寸
  widget_repository:
    path: packages/widget_repository
  utils:
    path: packages/utils
  db_storage:
    path: packages/db_storage
  widgets:
    path: packages/widgets
  authentication:
    path: packages/authentication
  app_config:
    path: packages/app_config
  app_update:
    path: packages/app_update
  components:
    path: packages/components
  widget_module:
    path: packages/widget_module
  old_fancy_mobile_ui:
    path: packages/old_fancy_mobile_ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/
    - assets/images/head_icon/
    - assets/images/widgets/
    - assets/flutter.db
    - assets/version.json

  fonts: # 配置字体，可配置多个，支持ttf和otf,ttc等字体资源
    - family: IndieFlower #字体名
      fonts:
        - asset: assets/fonts/IndieFlower-Regular.ttf
    - family: BalooBhai2 #字体名
      fonts:
        - asset: assets/fonts/BalooBhai2-Regular.ttf
    - family: Inconsolata #字体名
      fonts:
        - asset: assets/fonts/Inconsolata-Regular.ttf
    - family: Neucha #字体名
      fonts:
        - asset: assets/fonts/Neucha-Regular.ttf
    - family: ComicNeue #字体名
      fonts:
        - asset: assets/fonts/ComicNeue-Regular.ttf
    - family: CHOPS
      fonts:
        - asset: assets/fonts/CHOPS.TTF
    - family: TolyIcon
      fonts:
        - asset: assets/iconfont/iconfont.ttf

  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  module:
    androidX: true
    androidPackage: com.example.afjflutter
    iosBundleIdentifier: com.example.afjflutter
