name: flutter_unit
description: A new Flutter application.
publish_to: none
version: 2.8.0
author: 张风捷特烈 <1981462002@qq.com>
homepage: https://juejin.cn/user/149189281194766/posts


environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.4

  flutter_bloc: ^8.0.1 # 状态管理
  stream_transform: ^2.0.0
  equatable: ^2.0.3 # 相等辅助
  archive: ^3.3.6 # 解压
  package_info_plus: ^4.0.1 # 应用包信息
  r_upgrade: ^0.3.8+2 # 应用升级

  sqflite: ^2.0.2+1 # 数据库
  sqflite_common_ffi: ^2.1.1 # 数据库
  shared_preferences: ^2.0.13 # xml 固化
  path_provider: ^2.0.11 # 路径

  dio: ^4.0.4 # 网络请求
  jwt_decoder: ^2.0.1 # jwt 解析

  toggle_rotate: ^1.0.1
  flutter_star: ^1.0.2 # 星星组件
  dash_painter: ^1.0.2
  wrapper: ^1.0.2
  yaml_modify: ^1.0.1
  url_launcher: ^6.1.9 # url
  share_plus: ^7.0.1 # 文字分享
  flutter_svg: ^2.0.1
  intl: ^0.18.0
  platform: ^3.1.0
  image: ^3.1.0
  flutter_spinkit: ^5.1.0 # loading
  flutter_markdown: ^0.6.4 # markdown
#  file_selector: ^0.9.2+2
  file_picker: ^5.2.5
  window_manager: ^0.2.8 #桌面尺寸
  widget_repository:
    path: packages/widget_repository
  utils:
    path: packages/utils
  storage:
    path: packages/storage
  widgets:
    path: packages/widgets
  authentication:
    path: packages/authentication
  app:
    path: packages/app
  app_update:
    path: packages/app_update
  components:
    path: packages/components
  widget_module:
    path: packages/widget_module
#  old_fancy_mobile_ui:
#    path: packages/old_fancy_mobile_ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/
    - assets/images/head_icon/
    - assets/images/widgets/
    - assets/flutter.db
    - assets/version.json

  fonts: # 配置字体，可配置多个，支持ttf和otf,ttc等字体资源
    - family: TolyIcon
      fonts:
        - asset: assets/iconfont/iconfont.ttf
    - family: IndieFlower #字体名
      fonts:
        - asset: assets/fonts/IndieFlower-Regular.ttf
    - family: BalooBhai2 #字体名
      fonts:
        - asset: assets/fonts/BalooBhai2-Regular.ttf
    - family: Inconsolata #字体名
      fonts:
        - asset: assets/fonts/Inconsolata-Regular.ttf
    - family: Neucha #字体名
      fonts:
        - asset: assets/fonts/Neucha-Regular.ttf
    - family: ComicNeue #字体名
      fonts:
        - asset: assets/fonts/ComicNeue-Regular.ttf
    - family: CHOPS
      fonts:
        - asset: assets/fonts/CHOPS.TTF

  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  module:
    androidX: true
    androidPackage: com.example.afjandroid
    iosBundleIdentifier: com.alfred.AFJ-iOS











