name: Xcode - Build and Analyze

on:
  push:
    branches: [ "master", "dev*" ]
  pull_request:
    branches: [ "master", "dev*" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_ios:
    runs-on: macos-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
  
      - name: Setup React Native
        run: |
          cd ReactNative/RNSample/
          yarn install
          npm run ios-build
          
      - name: Setup Flutter
        run: |
          cd Flutter/FlutterUnit
          echo $PWD
          flutter clean
          flutter pub get
          flutter build ios --release --no-codesign
        
      - name: Pod install
        run: |
          cd ios
          echo $PWD
          pod install
 
      - name: Build
        run: |
          cd ios
          echo $PWD
          mkdir $PWD/build
          xcodebuild -workspace AFJ-iOS.xcworkspace -scheme AFJ-iOS-Debug -configuration Debug -destination 'platform=iOS Simulator,OS=16.4,name=iPhone 14'
